version: '3.8'



services:

  # Base de donn√©es

  db:

    image: mariadb:10.6

    container_name: wp_db

    restart: always

    environment:

      MYSQL_ROOT_PASSWORD: root

      MYSQL_DATABASE: wordpress

      MYSQL_USER: user

      MYSQL_PASSWORD: password

    volumes:

      - db_data:/var/lib/mysql



  # Moteur PHP (Wordpress sans Apache)

  wordpress:

    image: wordpress:php8.2-fpm

    container_name: wp_app

    restart: always

    depends_on:

      - db

    environment:

      WORDPRESS_DB_HOST: db

      WORDPRESS_DB_USER: user

      WORDPRESS_DB_PASSWORD: password

      WORDPRESS_DB_NAME: wordpress

    volumes:

      - wp_data:/var/www/html



  # Serveur Web (Nginx)

  nginx:

    image: nginx:latest

    container_name: wp_nginx

    restart: always

    ports:

      - "8080:80"

    volumes:

      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      - wp_data:/var/www/html

    depends_on:

      - wordpress



volumes:

  db_data:

  wp_data: